const state={students:JSON.parse(localStorage.getItem('sa_students')||'[]'),classes:JSON.parse(localStorage.getItem('sa_classes')||'[]'),attendance:JSON.parse(localStorage.getItem('sa_attendance')||'[]')};
const save=()=>{localStorage.setItem('sa_students',JSON.stringify(state.students));localStorage.setItem('sa_classes',JSON.stringify(state.classes));localStorage.setItem('sa_attendance',JSON.stringify(state.attendance));render()};
const today=()=>new Date().toISOString().slice(0,10);
function seed(){if(!state.students.length){state.students=[{id:'STU-001',name:'Aarav Sharma',className:'CSE-2A'}]}if(!state.classes.length){state.classes=[{id:'CLS-01',name:'CSE-2A',subject:'Computer Science'}]}if(!state.attendance.length){state.attendance=[{date:today(),studentId:'STU-001',present:true,time:new Date().toLocaleTimeString()}]}save()}
const qs=s=>document.querySelector(s); const qsa=s=>document.querySelectorAll(s);
function render(){qs('#studentCount').textContent=state.students.length;qs('#classCount').textContent=state.classes.length;qs('#sessionCount').textContent=new Set(state.attendance.map(a=>a.date)).size;const ta=state.students.map(s=>state.attendance.find(a=>a.date===today()&&a.studentId===s.id&&a.present)).filter(Boolean).length;const rate=state.students.length?Math.round(ta/state.students.length*100):0;qs('#todayRate').textContent=rate+'%';qs('#reportRate').textContent=rate+'%';qs('#presentCount').textContent=ta;qs('#absentCount').textContent=Math.max(0,state.students.length-ta);renderStudents();renderClasses();renderRegister();renderReports();renderBars()}
function renderStudents(){qs('#studentTable').innerHTML=state.students.length?state.students.map(s=>`<tr><td>${s.id}</td><td><b>${s.name}</b></td><td>${s.className}</td><td><span class="badge">Registered</span></td><td><button class="danger" onclick="removeStudent('${s.id}')">Remove</button></td></tr>`).join(''):`<tr><td colspan="5">No students yet.</td></tr>`}
window.removeStudent=id=>{state.students=state.students.filter(s=>s.id!==id);state.attendance=state.attendance.filter(a=>a.studentId!==id);save()};
function renderClasses(){qs('#classGrid').innerHTML=state.classes.length?state.classes.map(c=>`<article class="class-card"><strong>${c.name}</strong><p>${c.subject}</p><span>${state.students.filter(s=>s.className===c.name).length} students</span></article>`).join(''):'<div class="panel">No classes added yet.</div>'}
function renderRegister(){qs('#todayRegister').innerHTML=state.students.length?state.students.map(s=>{const p=state.attendance.find(a=>a.date===today()&&a.studentId===s.id&&a.present);return `<div class="register-row"><span>${s.name}<small> · ${s.className}</small></span><span class="${p?'present':'absent'}">${p?'Present':'Absent'}</span></div>`}).join(''):'<p>No students registered.</p>'}
function renderReports(){const list=state.attendance.slice().reverse().slice(0,15);qs('#recentAttendance').innerHTML=list.length?list.map(a=>{const s=state.students.find(x=>x.id===a.studentId);return `<div class="register-row"><span>${s?s.name:a.studentId}</span><span class="present">${a.date} · ${a.time||''}</span></div>`}).join(''):'<p>No attendance records.</p>'}
function renderBars(){const wrap=qs('#weeklyBars'),days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const iso=d.toISOString().slice(0,10),count=state.attendance.filter(a=>a.date===iso&&a.present).length,rate=state.students.length?Math.round(count/state.students.length*100):0;days.push({label:d.toLocaleDateString(undefined,{weekday:'short'}),rate})}wrap.innerHTML=days.map(x=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(5,x.rate)}%" title="${x.rate}%"></div><div class="bar-label">${x.label}</div></div>`).join('')}
function openView(view){qsa('.view').forEach(x=>x.classList.remove('active-view'));qs('#'+view).classList.add('active-view');qsa('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const meta={dashboard:['Dashboard','Overview of your attendance system'],students:['Students','Manage registered learners'],classes:['Classes','Organize your active classes'],attendance:['Take Attendance','Record today’s attendance'],reports:['Reports','Attendance analytics and export']};qs('#pageTitle').textContent=meta[view][0];qs('#pageSubtitle').textContent=meta[view][1]}
qsa('[data-view]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)));
const modal=qs('#modal');function modalOpen(type){qs('#modalTitle').textContent=type==='student'?'Add Student':'Add Class';qs('#nameInput').placeholder=type==='student'?'Student name':'Class name';qs('#classInput').placeholder=type==='student'?'e.g. CSE-2A':'Subject';qs('#modalForm').dataset.type=type;modal.classList.remove('hidden');qs('#nameInput').focus()}qs('#addStudentBtn').onclick=()=>modalOpen('student');qs('#addClassBtn').onclick=()=>modalOpen('class');qs('#closeModal').onclick=()=>modal.classList.add('hidden');
qs('#modalForm').onsubmit=e=>{e.preventDefault();const type=e.target.dataset.type,name=qs('#nameInput').value.trim(),second=qs('#classInput').value.trim();if(type==='student')state.students.push({id:'STU-'+String(state.students.length+1).padStart(3,'0'),name,className:second});else state.classes.push({id:'CLS-'+String(state.classes.length+1).padStart(2,'0'),name,subject:second});modal.classList.add('hidden');e.target.reset();save()};
let stream=null;qs('#startCamera').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:true});qs('#camera').srcObject=stream;qs('#cameraMessage').textContent='Camera active. Select Mark Present to record a session.'}catch(e){qs('#cameraMessage').textContent='Camera permission was unavailable. You can still use the register manually.'}};qs('#stopCamera').onclick=()=>{if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;qs('#camera').srcObject=null;qs('#cameraMessage').textContent='Camera is off.'};
qs('#markPresent').onclick=()=>{if(!state.students.length)return alert('Add a student first.');const id=state.students[0].id;if(!state.attendance.some(a=>a.date===today()&&a.studentId===id)){state.attendance.push({date:today(),studentId:id,present:true,time:new Date().toLocaleTimeString()});save();alert(`${state.students[0].name} marked present.`)}else alert('Attendance is already recorded for today.')};
qs('#exportBtn').onclick=()=>{const rows=[['Date','Student ID','Student','Status','Time'],...state.attendance.map(a=>{const s=state.students.find(x=>x.id===a.studentId);return[a.date,a.studentId,s?.name||'',a.present?'Present':'Absent',a.time||'']})];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='attendance-report.csv';a.click();URL.revokeObjectURL(a.href)};
seed();render();